name: psggw
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  dio: ^5.3.4
  flutter_colorpicker: ^1.0.3
  easy_localization: ^3.0.3
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1


flutter:
  assets:
    - assets/translations/
  uses-material-design: true
