name: silvertimetable
description: SGGW schedule app
version: 4.3.0+430000

environment:
  sdk: ">=3.1.4 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  dynamic_color: ^1.6.9
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.2
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  bloc_test: ^9.1.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/translations/
  uses-material-design: true
