name: psggw
description: A new Flutter project.
publish_to: " "
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_symbols_icons: ^4.2711.0
  hive: ^2.0.4
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  dio: ^5.3.4
  flutter_colorpicker: ^1.0.3
  easy_localization: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1


flutter:
  assets:
    - assets/translations/
  uses-material-design: true
