name: silvertimetable
description: SGGW schedule app
version: 4.3.0+430000

environment:
  sdk: ">=3.1.4 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  image_path: "assets/images/icon.png"
  # see https://pub.dev/packages/flutter_launcher_icons#mag-attributes for other attributes

dependencies:
  animations: ^2.0.11
  bloc_concurrency: ^0.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dynamic_color: ^1.6.9
  easy_localization: ^3.0.3
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  material_symbols_icons: ^4.2719.1
  mockito: ^5.4.4
  overlay_support: ^2.1.0
  package_info_plus: ">=5.0.1 <8.0.0"
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  build_test: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  assets:
    - assets/translations/
    - assets/images/
  uses-material-design: true
