name: silvertimetable
description: SGGW schedule app
version: 4.3.0+430000

environment:
  sdk: ">=3.1.4 <4.0.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  image_path: "assets/images/icon.png"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dynamic_color: ^1.6.9
  easy_localization: ^3.0.3
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.2
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  build_test: ^2.2.2
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter:
  assets:
    - assets/translations/
    - assets/images/
  uses-material-design: true

#  image_path: "assets/images/icon.png"
#   # image_path_android: "assets/images/icon-710x599-android.png"
#   # image_path_ios: "assets/images/icon-1024x1024.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
#   adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#   adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
#   adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
#   background_color_ios: "#ffffff"
#   web:
#     generate: true
#     image_path: "assets/images/icon.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/images/icon.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/images/icon.png"