on:
  workflow_call:
    inputs:
      web-href:
        description: "Base Href for web app"
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      - name: Get packages
        run: flutter pub get

  android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Android
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  web:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.inputs.web-href }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
