name: Build Web and Android
on:
  workflow_call:
    inputs:
      web-href:
        description: "Base Href for web app"
        required: true
        type: string

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      - name: Get packages
        run: flutter pub get
      - name: Create Android SDK directory
        run: sudo mkdir -p /usr/local/lib/android/sdk
      - name: chown Android SDK
        run: sudo chown -R $USER:$USER /usr/local/lib/android/sdk
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/pubspec.yaml') }}
      - name: Build Android
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      - name: Get packages
        run: flutter pub get
      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.inputs.web-href }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
