name: Build Web and Android
on:
  workflow_call:
    inputs:
      web-href:
        description: "Base Href for web app"
        required: true
        type: string

jobs:
  android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"
      # - name: Cache Gradle
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.gradle
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Cache Android Build Tools
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/build-tools
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/android*') }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: android-actions/setup-android@v2
        with:
          log-accepted-android-sdk-licenses: false
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      - run: flutter pub get
      - name: Build Android
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"
      - name: Get packages
        run: flutter pub get
      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.inputs.web-href }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
