name: Publish to GitHub Pages

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - devops-changes

jobs:
  build:
    uses: "./.github/workflows/build.yaml"
    with:
      web-href: "${{ github.event.repository.name }}"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish APK release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: build
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app-release.apk
          prerelease: true


  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: build
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: Dockerfile
          sparse-checkout-cone-mode: false
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: web
          path: build/web
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write # to deploy to Pages
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
